from ProteinDT.models.score_networks.ToyScoreNetwork import ToyScoreNetwork
from ProteinDT.models.score_networks.RNNScoreNetwork import RNNScoreNetwork
from ProteinDT.models.score_networks.BertScoreNetwork import BertScoreNetwork